export const PreHospitalCare = {
  ambulanceStation: "",
  shiftCode: "",
  region: "",
  kmReading: "",
  callNumber: "",
  callerName: "",
  dispatcher: "",
  comments: "",
  patientName: "",
  age: "",
  address: "",
  telephone: "",
  idPassportNumber: "",
  contactPersonName: "",
  contactPersonTelephone: "",
  chiefComplaint: "",
  descriptionOfProblem: "",
  recentMedicalHistory: "",
  vitalSigns: "",
  bp: "",
  pulseRate: "",
  respRate: "",
  spO2: "",
  temp: "",
  additionalInterventions: "",
  fieldDiagnosisObservations: "",
  receivingFacility: "",
  receivingDepartment: "",
  receivingDoctorOrNurse: "",
  signature: "",
  receivingPersonnelName: "",
  receivingPersonnelSignature: "",
  emt1ServiceNumber: "",
  emt1Signature: "",
  emt2ServiceNumber: "",
  emt2Signature: "",
  emtGaveOralReportToName: "",
};

export const PreBilling = {
  ambulanceStationNumber: "",
  patientFirstName: "",
  patientLastName: "",
};
