export const PreHospitalCare = {
  ambulanceStation: "",
  shiftCode: "",
  region: "",
  dispatchDate: "",
  time: "",
  timeAmbulanceAssigned: "",
  timeAmbulanceArrivedScene: "",
  timeAmbulanceLeftScene: "",
  timeArrivedFacility: "",
  vitalSignsTime: "",
  dateAndTime: "",
  patientHandoffDate: "",
  patientHandoffTime: "",
  emtDateTime: "",
  kmReading: "",
  callNumber: "",
  callerName: "",
  dispatcher: "",
  comments: "",
  patientName: "",
  age: "",
  address: "",
  telephone: "",
  idPassportNumber: "",
  contactPersonName: "",
  contactPersonTelephone: "",
  chiefComplaint: "",
  descriptionOfProblem: "",
  recentMedicalHistory: "",
  vitalSigns: "",
  bp: "",
  pulseRate: "",
  respRate: "",
  spO2: "",
  temp: "",
  additionalInterventions: "",
  fieldDiagnosisObservations: "",
  receivingFacility: "",
  receivingDepartment: "",
  receivingDoctorOrNurse: "",
  signature: "",
  receivingPersonnelName: "",
  receivingPersonnelSignature: "",
  emt1ServiceNumber: "",
  emt1Signature: "",
  emt2ServiceNumber: "",
  emt2Signature: "",
  emtGaveOralReportToName: "",
  serviceUnitContact: [
    "residence",
    "other",
    "hospitalClinic",
    "officePublic",
    "publicPlace",
  ],
  gender: ["male", "female"],
  ambulanceType: ["private", "basicLifeSupport", "advancedLifeSupport"],
  callType: ["emergency", "urgent", "routine"],
  reasonForTransfer: ["obstetrics", "dialysis", "physiotherapy", "other"],
  arrivedAtScene: [
    "ambulanceArrival",
    "arrivalAtFacility",
    "departedScene",
    "arrivedAtBase",
    "backInService",
  ],
  relationship: ["spouse", "other", "fatherMother"],
  patientRefusedTreatment: ["yes", "no"],
  bodyPartInvolved: [
    "thorax",
    "other",
    "headNeck",
    "lowerAbdomen",
    "upperAbdomen",
    "lowerExtremities",
    "upperExtremities",
    "reproductiveTract",
  ],
  sourceOfInformation: [
    "patient",
    "nurse",
    "doctor",
    "bystander",
    "other",
    "relativeFriend",
  ],
  typeOfTrauma: [
    "trauma",
    "roadTrafficCollision",
    "industrialAccident",
    "mentalDisorder",
    "other",
  ],
  triage: ["red", "yellow", "green", "black"],
  breathing: ["adequate", "inadequate"],
  circulation: ["pulseAbsent", "pulsePresent"],
  consciousness: ["conscious", "unconscious"],
  patientCondition: ["improved", "unchanged", "deteriorated", "diedEnRoute"],
  docOnlyPatientCondition: ["red", "yellow", "green", "black"],
};

export const PreBillingCode = {
  ambulanceStationNumber: "",
  patientFirstName: "",
  patientLastName: "",
  dispatchDate: "",
  timeLeftBase: "",
  ambulanceStationNumber: "",
  patientFirstName: "",
  patientLastName: "",
  ageDateOfBirth: "",
  insuranceOther: "",
  insuranceCompany: "",
  emtCompletingThisForm: "",
  emtName: "",
  emtSignature: "",
  emtDateTime: "",
  generalMedicalOther: "",
  patientMechanismOfInjuryOther: "",
  otherProblemNotListed: "",
  sex: "",
  insurance: "",
  airway: "",
  cardiovascular: "",
  earMouthNoseThroat: "",
  environmental: "",
  eyes: "",
  gastrointestinal: "",
  generalMedical: "",
  gynaecological: "",
  maternalObstetric: "",
  musculoskeletalInjury: "",
  neurological: "",
  psychiatric: "",
  respiratory: "",
  urologic: "",
  skin: "",
  patientMechanismOfInjury: "",
  roadTrafficAccidentPatientWasA: "",
  healthy: "",
  equipmentAirway: "",
  equipmentCardiovascular: "",
  equipmentEarMouth: "",
  equipmentGeneralMedical: "",
  equipmentMusculoskeletal: "",
  equipmentPsychiatric: "",
  equipmentRespiratory: "",
  equipmentMusculoskeletal_other: "",
  otherEquipmentUsed: "",
};
